import React, { useState } from 'react';
import { X, Settings, Check } from 'lucide-react';
import { MachineConfig } from '../types';
import { PONS_V2_CONFIG } from '../contracts';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: MachineConfig;
  onSaveConfig: (config: MachineConfig) => void;
}

export const SettingsModal: React.FC<SettingsModalProps> = ({
  isOpen,
  onClose,
  config,
  onSaveConfig,
}) => {
  const [formData, setFormData] = useState<MachineConfig>({ ...config });

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSaveConfig(formData);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-[#151c27] sketch-box w-full max-w-xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden border-2 border-slate-600">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 bg-[#111722] border-b-2 border-dashed border-slate-700">
          <div className="flex items-center gap-2">
            <Settings className="w-5 h-5 text-amber-400" />
            <div>
              <h3 className="font-sketch text-base font-bold text-white">Machine Configuration</h3>
              <p className="font-hand text-xs text-slate-400">
                Setup your token contract and execution thresholds
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-5 overflow-y-auto space-y-4 text-xs font-hand text-base">
          {/* Token Symbol & Name */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-amber-300 font-sketch text-xs mb-1">Token Symbol</label>
              <input
                type="text"
                value={formData.tokenSymbol}
                onChange={(e) => setFormData({ ...formData, tokenSymbol: e.target.value.toUpperCase() })}
                className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white font-mono focus:border-amber-400 focus:outline-none"
                placeholder="PONS"
              />
            </div>
            <div>
              <label className="block text-amber-300 font-sketch text-xs mb-1">Token Name</label>
              <input
                type="text"
                value={formData.tokenName}
                onChange={(e) => setFormData({ ...formData, tokenName: e.target.value })}
                className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white focus:border-amber-400 focus:outline-none"
                placeholder="Pons Machine Token"
              />
            </div>
          </div>

          {/* Token CA */}
          <div>
            <label className="block text-amber-300 font-sketch text-xs mb-1">
              Token Contract Address (CA)
            </label>
            <input
              type="text"
              value={formData.tokenAddress}
              onChange={(e) => setFormData({ ...formData, tokenAddress: e.target.value })}
              className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white font-mono focus:border-amber-400 focus:outline-none text-xs"
              placeholder="0x..."
            />
          </div>

          {/* Curve CA */}
          <div>
            <label className="block text-amber-300 font-sketch text-xs mb-1">
              Pons Bonding Curve Address
            </label>
            <input
              type="text"
              value={formData.curveAddress}
              onChange={(e) => setFormData({ ...formData, curveAddress: e.target.value })}
              className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white font-mono focus:border-amber-400 focus:outline-none text-xs"
              placeholder="0x..."
            />
            <span className="text-xs text-slate-500 font-hand mt-0.5 block">
              Generated by Pons Factory upon launching your token.
            </span>
          </div>

          {/* Threshold & Speed */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-amber-300 font-sketch text-xs mb-1">
                Claim Fee Threshold (ETH)
              </label>
              <input
                type="number"
                step="0.001"
                min="0.0001"
                value={formData.claimThresholdETH}
                onChange={(e) =>
                  setFormData({ ...formData, claimThresholdETH: parseFloat(e.target.value) || 0.01 })
                }
                className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white font-mono focus:border-amber-400 focus:outline-none"
              />
              <span className="text-xs text-slate-500 font-hand mt-0.5 block">
                Triggers claim() when Escrow ≥ this amount.
              </span>
            </div>

            <div>
              <label className="block text-amber-300 font-sketch text-xs mb-1">
                Cycle Step Interval (Seconds)
              </label>
              <input
                type="number"
                min="2"
                max="60"
                value={formData.cycleIntervalSeconds}
                onChange={(e) =>
                  setFormData({ ...formData, cycleIntervalSeconds: parseInt(e.target.value) || 5 })
                }
                className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white font-mono focus:border-amber-400 focus:outline-none"
              />
              <span className="text-xs text-slate-500 font-hand mt-0.5 block">
                Rotation speed per stage.
              </span>
            </div>
          </div>

          {/* Dead Burn Address (Fixed) */}
          <div>
            <label className="block text-amber-300 font-sketch text-xs mb-1">
              Dead Sink Address (Permanent Burn)
            </label>
            <input
              type="text"
              readOnly
              value={PONS_V2_CONFIG.contracts.deadAddress}
              className="w-full px-3 py-2 bg-[#0d1219]/60 border border-slate-800 rounded-lg text-slate-500 font-mono text-xs select-all cursor-not-allowed"
            />
          </div>

          {/* RPC URL */}
          <div>
            <label className="block text-amber-300 font-sketch text-xs mb-1">
              Robinhood Chain RPC URL
            </label>
            <input
              type="text"
              value={formData.rpcUrl}
              onChange={(e) => setFormData({ ...formData, rpcUrl: e.target.value })}
              className="w-full px-3 py-2 bg-[#0d1219] border border-slate-700 rounded-lg text-white font-mono focus:border-amber-400 focus:outline-none text-xs"
              placeholder="https://rpc.robinhood.org"
            />
          </div>

          {/* Action buttons */}
          <div className="pt-3 border-t-2 border-dashed border-slate-700 flex items-center justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 font-sketch rounded-lg transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-5 py-2 bg-amber-400 hover:bg-amber-300 text-slate-950 font-sketch font-bold rounded-lg flex items-center gap-1.5 transition-colors cursor-pointer shadow-[2px_2px_0px_#000]"
            >
              <Check className="w-4 h-4" />
              <span>Save Configuration</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
